# Site
name: "7Targets Blog"
title: "7Targets Blog"
description: "Applying Artificial Intelligence to Sales"
logo: 'assets/images/7ts-logo.png'
favicon: 'assets/images/logo1.png'
baseurl: /
url: https://blog.7targets.ai
google_analytics: 'UA-140617154-1'
# disqus: 'ggnagarkar'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: info@7targets.com

# Authors
authors:
  GG:
    name: GG Nagarkar
    display_name: GG
    avatar: 'assets/images/GG.png'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: gg@7targets.com
    web: https://www.linkedin.com/in/gunanandnagarkar
    twitter: https://twitter.com/ggnagarkar
    description: "Gunanand (aka GG) is known for bringing 3 things on board – Efficiency, Engagement and Enthusiasm. Presently focused on creating strategic solutions in Sales and Marketing domain with optimal use of AI/ML technology.

Background: Infrastructure, Cloud, Application Monitoring, Event Management, Root Causal Analysis, BSM integrations, Big Data Analytics.

Success: Founded and sold Opex Software/REAN cloud to Hitachi Vantara. Big contributor in the $950m DoD Cloud deal. (pre-JEDI deal)"
  Sanju:
    name: Sanju Burkule
    display_name: Sanju
    avatar: 'assets/images/sanju.jpeg'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: sanju.burkule@7targets.com
    web: https://www.linkedin.com/in/sanjuburkule
    twitter: https://twitter.com/sanjuburkule
    description: "Sanju is a serial entrepreneur. 2 decades of experience. Loves automating stuff. Recent obsession is around adding intelligence in marketing and sales solutions. He is currently focusing on a simple but very important problem of figuring out the best ways to intelligently respond to leads on time (not too fast, and not too late) to help get a meeting.

His new mission is ‘Personalisation at scale for all at reasonably low cost’.

Background: Developer. Founded and sold Opex Software/REAN cloud to Hitachi Vantara. Was lucky to be a contributor in the $950m DoD Cloud deal (pre JEDI deal)."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
